function [RptgenML_CReport1] = buildprofile_anal
%BUILDPROFILE_ANAL
 
%  Auto-generated by MATLAB on 17-Oct-2013 22:20:10
 
% Create RptgenML.CReport
RptgenML_CReport1 = RptgenML.CReport('Description','Profile Analysis',...
'Format','pdf-fop',...
'Stylesheet','default-fo');
% setedit(RptgenML_CReport1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph1 = rptgen.cfr_paragraph;
rptgen_cfr_text1 = rptgen.cfr_text;
set(rptgen_cfr_paragraph1,'ParaTextComp',rptgen_cfr_text1);
setParent(rptgen_cfr_paragraph1,RptgenML_CReport1);
 
% Create rptgen.crg_tds
rptgen_crg_tds1 = rptgen.crg_tds('prefixstring','');
setParent(rptgen_crg_tds1,rptgen_cfr_paragraph1);
 
% Create rptgen.cfr_table
rptgen_cfr_table1 = rptgen.cfr_table('Source','profile_anal_table',...
'TableTitle','Profiles and Stats');
setParent(rptgen_cfr_table1,rptgen_cfr_paragraph1);
 
% Create rptgen_hg.chg_fig_loop
rptgen_hg_chg_fig_loop1 = rptgen_hg.chg_fig_loop('TagList',{'profile_anal'},...
'LoopType','TAG');
setParent(rptgen_hg_chg_fig_loop1,RptgenML_CReport1);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap1 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'MaxViewportSize',[7 9]);
setParent(rptgen_hg_chg_fig_snap1,rptgen_hg_chg_fig_loop1);
 
