% DIFFUSION
%
% Files
%   buildprofile_anal   - BUILDPROFILE_ANAL (autogenerated by MATLAB)
%   calcADC             - calcADC Calculate ADC by linear fitting to log of data
%   colwheel            - Generate a colour wheel. Projection of radius to sphere
%   cond_diff           - Diffusion directions condition number
%   create_colour_FA    - Jack Harmer
%   d2cfa               - Diffusion tensor to colour coded FA map
%   d2eig               - d2eig Single tensor to sorted eigenvectors and values
%   d2tshow             - d2tshow
%   display_dti_arrows  - Display colour DTI tensors in 2D slice
%   displayADC          - Displays ADCs as a montage with a numbered colorbar
%   dmf2d               - DICOM MultiFrmae to Diffusion Tensor
%   dti_direc           - DTI Directions
%   dwi2tensor          - DWI to tensors using B matrix or gradients 
%   invariantsb         - Vectorised computation of DWI FA, RA or mean
%   noddi2Protocol      - Make a NODDI protocol
%   noddi_batch_fitting - Calls NODDI fitting routines
%   noddi_params_view   - noddi_params_view(paramsfile)
%   noddi_qa            - Quality Assurance on NODDI (DTI)
%   normsb              - normsb for the tensor field Ds
%   profile_anal        - Analysis of ADC profiles for SI Joints
%   quiver_colour       - Coloured quivers...
%   stretch_exp         - Fit a stretched exponential to diffusion data
%   vec2col             - Vector (eigenvector direction) to colour
%   writeADC            - writeADC  Write DICOM ADC !!! Replaced by writeDicom
