% MATLAB script to run VERDICT processing on specified patients

% Define list of patient numbers
PatNums = [...
    "BAR_003",...
%     "BAR_005",...
%     "BAR_006",...
%     "BAR_009",...
%     "BAR_004",...
%     "BAR_033",...
%     "INN_019",...
%     "BAR_012"
%     "INN_087",...
%     "INN_099",...
%     "INN_109",...
%     "BAR_035",...
%     "BAR_017",...
%     "BAR_028"
    ];


% Model type
ModelType = "No VASC Reduced Rs";
solver = 'lsqnonneg';

% Run VERDICT processing
for PatNum = PatNums
    disp(["----------->" PatNum])
    VERDICT(PatNum, ModelType, solver = solver);
end