function [RptgenML_CReport1] = buildroianal
%BUILDROIANAL
 
%  Auto-generated by MATLAB on 27-Apr-2018 14:46:02
 
% Create RptgenML.CReport
RptgenML_CReport1 = RptgenML.CReport('Description',...
'Auto-generated report initiated from roianal','Format','pdf-fop',...
'Stylesheet','default-fo');
% setedit(RptgenML_CReport1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph1 = rptgen.cfr_paragraph('ParaTitle',...
'Auto-generated report from roianal','TitleType','specify');
rptgen_cfr_text1 = rptgen.cfr_text;
set(rptgen_cfr_paragraph1,'ParaTextComp',rptgen_cfr_text1);
setParent(rptgen_cfr_paragraph1,RptgenML_CReport1);
 
% Create rptgen.crg_tds
rptgen_crg_tds1 = rptgen.crg_tds('prefixstring','Report created:');
setParent(rptgen_crg_tds1,rptgen_cfr_paragraph1);
 
% Create rptgen.cfr_list
rptgen_cfr_list1 = rptgen.cfr_list('Source','roianal_list',...
'ListTitle','ROI LIST');
setParent(rptgen_cfr_list1,rptgen_cfr_paragraph1);
 
% Create rptgen_hg.chg_fig_loop
rptgen_hg_chg_fig_loop1 = rptgen_hg.chg_fig_loop('TagList',...
{'roianalfig','roianal_montage','roianal_lineprofile','roianal_athresh','roianal_histogram','roianal_time','roianal_snapshot'},...
'LoopType','TAG');
setParent(rptgen_hg_chg_fig_loop1,rptgen_cfr_paragraph1);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap1 = rptgen_hg.chg_fig_snap('TitleType','name',...
'ImageFormat','jpeg90',...
'MaxViewportSize',[7 9]);
setParent(rptgen_hg_chg_fig_snap1,rptgen_hg_chg_fig_loop1);
 
