function [fitresult, gof] = T1fit(All_TE, current_agar)
%CREATEFIT(ALL_TE,CURRENT_AGAR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : All_TE
%      Y Output: current_agar
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Mar-2021 15:05:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( All_TE, current_agar );

% Set up fittype and options.
ft = fittype( '-a*exp(b*x) + c*(1-exp(b*x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-1000000 -1 -1000000];
opts.StartPoint = [70000 5e-06 -0.0006];
opts.Upper = [1000000 1 100000];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'current_agar vs. All_TE', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'All_TE', 'Interpreter', 'none' );
ylabel( 'current_agar', 'Interpreter', 'none' );
grid on


